AWSTemplateFormatVersion: '2010-09-09'
Description:  >
  Stack for Superset on EMR. Deploys an EMR cluster.
Parameters:
  ProjectName:
    Description: Project name that is prefixed to resource names
    Type: String
  EnvironmentName:
    Description: Environment name (e.g., Development, Test, Production)
    Type: String
  ClusterOwner:
    Description: Owner of Cluster (e.g., Data Analysts, Marketing, Finance)
    Type: String
  Ec2SubnetId:
    Description: The Subnet Id where the cluster will be deployed
    Type: String
  TerminationProtected:
    Description: Set auto-termination on or off
    Type: String
  Ec2KeyName:
    Description: EMR Master node SSH Keypair name
    Type: String
  MasterInstanceCount:
    Description: Number of Master nodes
    Type: Number
  MasterInstanceType:
    Description: EC2 instance type for Master nodes
    Type: String
  CoreInstanceCount:
    Description: Number of Core nodes
    Type: Number
  CoreInstanceType:
    Description: EC2 instance type for Core nodes
    Type: String
  ReleaseLabel:
    Description: Version of EMR to deploy to cluster
    Type: String
  EbsRootVolumeSize:
    Description: Size in GBs of EBS root volume
    Type: String
  BootstrapBucket:
    Description: Name of S3 bucket where EMR bootstrap script is located
    Type: String
Resources:
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', ['superset-emr-demo-logs', !Ref 'AWS::AccountId', !Ref 'AWS::Region']]
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName} Logs Bucket
  Cluster:
    Type: AWS::EMR::Cluster
    Properties:
      Applications:
        - Name: 'Ganglia'
        - Name: 'Hadoop'
        - Name: 'Hive'
        - Name: 'Spark'
        - Name: 'Zeppelin'
        - Name: 'JupyterEnterpriseGateway' # only for new v5.31.0 and v6.2.0
        - Name: 'Presto'
      BootstrapActions:
        - Name: bootstrap-script
          ScriptBootstrapAction:
            Path: !Join ['', ['s3://', !Ref BootstrapBucket, '/bootstrap_actions.sh']]
      Configurations:
        - Classification: hive-site
          ConfigurationProperties:
            hive.metastore.client.factory.class: 'com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory'
        - Classification: spark-hive-site
          ConfigurationProperties:
            hive.metastore.client.factory.class: 'com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory'
        - Classification: presto-connector-hive
          ConfigurationProperties:
            hive.metastore.glue.datacatalog.enabled: true
      EbsRootVolumeSize: !Ref EbsRootVolumeSize
      Instances:
        Ec2KeyName: !Ref Ec2KeyName
        MasterInstanceGroup:
          InstanceCount: !Ref MasterInstanceCount
          InstanceType: !Ref MasterInstanceType
          Market: ON_DEMAND
          Name: MASTER
        CoreInstanceGroup:
          InstanceCount: !Ref CoreInstanceCount
          InstanceType: !Ref CoreInstanceType
          Market: ON_DEMAND
          Name: CORE
        TerminationProtected: !Ref TerminationProtected
        Ec2SubnetId: !Ref Ec2SubnetId
      Name: 'demo-cluster-cloudformation'
      JobFlowRole: 'EMR_EC2_DefaultRole'
      ServiceRole: 'EMR_DefaultRole'
      ReleaseLabel: !Ref ReleaseLabel
      VisibleToAllUsers: true
      LogUri: !Sub s3://${LogsBucket}/
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName} Cluster
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Owner
          Value: !Ref ClusterOwner
    DependsOn:
      - LogsBucket
  ClusterMasterPublicDNS:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/emr_superset_demo/master_public_dns'
      Type: String
      Value: !GetAtt Cluster.MasterPublicDNS
      Description: Master Node Public DNS
      Tags:
        Environment: !Ref EnvironmentName
